name: Test Action

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-broker:
    name: Test HiveMQ 4 Docker image version [${{ matrix.version }}]

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: ['4.4.4', 'latest']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start HiveMQ 4
        uses: ./
        with:
          version: ${{ matrix.version }}
