name: Start HiveMQ Broker

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-broker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [4.4.4, latest]

    name: Start HiveMQ Broker [${{ matrix.version }}]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start HiveMQ Broker
        uses: ./
        with:
          version: ${{ matrix.version }}
